### ISSUE TITLE
如果遇到ImportError: cannot import name ‘soft_unicode’ from 'markupsafe’要这样处理

### ISSUE THREAD

**Issue by df13954** [coder-pig/hzwz-markdown-wx#1]
导入ide工具很顺利，安装了几个依赖之后，run，报错：

```
ImportError: cannot import name ‘soft_unicode’ from 'markupsafe’
```
这个时候可以把已经安装的版本卸载，安装旧版本就行了。
```
pip install markupsafe==2.0.1
```
希望大佬把这个主意的地方写到文档中，不然下一个入坑的会卡主

**Comment by df13954** [comment]
顺便问问大佬，这个工具转换出来的html要怎么使用？在微信公众号发布页面，把html里面的内容贴进去吗，我现在贴进去了，预览文章无效果，看到的是各种html标签。

**Comment by coder-pig** [comment]
F12，点箭头定位到输入区域，把生成的html Copy进去

**Comment by coder-pig** [comment]
我的话，用到了另一个插件 →  壹伴助手，点这个，然后Copy html覆盖下这里，点击保存为草稿就可以正常预览了

![image](https://user-images.githubusercontent.com/6879486/211440792-987aaf80-b676-49ba-b407-dd33058ab387.png)

**Comment by coder-pig** [comment]
> 导入ide工具很顺利，安装了几个依赖之后，run，报错：
> 
> ```
> ImportError: cannot import name ‘soft_unicode’ from 'markupsafe’
> ```
> 
> 这个时候可以把已经安装的版本卸载，安装旧版本就行了。
> 
> ```
> pip install markupsafe==2.0.1
> ```
> 
> 希望大佬把这个主意的地方写到文档中，不然下一个入坑的会卡主

错误及解决方法已添加到README.md中，感谢提出~

**Comment by df13954** [comment]
按照操作成功！
